### ISSUE TITLE
(Windows) pcconfig.json not read - pull cannot be performed

### ISSUE THREAD

**Issue by torbenvanassche** [playcanvas/playcanvas-sync#20]
splitting the data between the `.pcconfig` file and `pcconfig.json` does not appear to work. 
When I merge the content of the 2 files it does work (concluding that the data I have in there is correct and something else is wrong)

![Code_AluidlOqaV](https://user-images.githubusercontent.com/38832704/123268428-4e937380-d4fe-11eb-8d29-2c9f09ea1eeb.png)

I would like to suggest a potential fix for this to allow `node pcsync.js pull PROJECTID BRANCHID TARGET_DIR`
This should allow a degree of freedom to the user so they can set up commands in their package.json to pull data without the need of the json file.

**Comment by zachpeterpaul** [comment]
To find pcconfig.json (in the target dir), pcsync needs to know where the target dir is, so PLAYCANVAS_TARGET_DIR can only be set in .pcconfig in your home directory or via an environment variable. I hope this helps, otherwise please let us know which variables you are trying to set in each file when it doesn't work.
